export { default as BannerSection } from './BannerSection'
export { default as ChartSection } from './ChartSection'
export { default as CommentSection } from './CommentSection'
export { default as FaqProductSection } from './FaqProductSection'
export { default as FaqSection } from './FaqSection'
export { default as ModelProductSection } from './ModelProductSection'
export { default as ReviewSection } from './ReviewSection'
